# Объемы продаж игр разного жанра 

- Автор: Семенычев Никита Дмитриевич 
- Дата: 28.09.2026

### Цели и задачи проекта

В данной тетради будет использован датасет new_games.csv, который содержит информацию о продажах игр разных жанров и платформ, а также пользовательские и экспертные оценки игр. При работе с датасетом поставлены задачи: познакомиться с данными, найти ошибки и предобработать их, провести фильтрацию и категоризацию данных. Цель - выделить топ-7 платформ по количеству игр, выпущенных с 2000 по 2013 год включительно.

### Описание данных

В проекте будут использованы данные датасета new_games.csv с таким описанием данных:

- Name — название игры.
- Platform — название платформы.
- Year of Release — год выпуска игры.
- Genre — жанр игры.
- NA sales — продажи в Северной Америке (в миллионах проданных копий).
- EU sales — продажи в Европе (в миллионах проданных копий).
- JP sales — продажи в Японии (в миллионах проданных копий).
- Other sales — продажи в других странах (в миллионах проданных копий).
- Critic Score — оценка критиков (от 0 до 100).
- User Score — оценка пользователей (от 0 до 10).
- Rating — рейтинг организации ESRB (англ. Entertainment Software Rating Board). Эта ассоциация определяет рейтинг компьютерных игр и присваивает им подходящую возрастную категорию.

### Содержимое проекта

1. Загрузка данных и первое знакомство с ними
2. Проверка ошибок и предобработка:

    - 2.1. Метки столбцов
    - 2.2. Типы данных
    - 2.3. Пропуски
    - 2.4. Явные и неявные дубликаты
3. Фильтрация данных по периоду
4. Категоризация игр по оценкам
5. Итоговые выводы

## Загрузка данных и знакомство с ними

- Загрузил необходимые библиотеки Python и данные датасета `/datasets/new_games.csv`.

In [1]:
import pandas as pd

In [2]:
URL = 'D:/DS_Projects/new_games/new_games.csv'
games = pd.read_csv(URL)

- Познакомился с данными: вывел первые строки и результат метода `info()`.

In [3]:
games.head(20)

,Name,Platform,Year of Release,Genre,NA sales,EU sales,JP sales,Other sales,Critic Score,User Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,23.20,2.26,4.22,0.58,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,11.28,9.14,6.5,2.88,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,14.44,6.94,4.7,2.24,87.0,8.4,E
9,Duck Hunt,NES,1984.0,Shooter,26.93,0.63,0.28,0.47,NaN,NaN,NaN
10,Nintendogs,DS,2005.0,Simulation,9.05,10.95,1.93,2.74,NaN,NaN,NaN
11,Mario Kart DS,DS,2005.0,Racing,9.71,7.47,4.13,1.90,91.0,8.6,E
12,Pokemon Gold/Pokemon Silver,GB,1999.0,Role-Playing,9.00,6.18,7.2,0.71,NaN,NaN,NaN
13,Wii Fit,Wii,2007.0,Sports,8.92,8.03,3.6,2.15,80.0,7.7,E
14,Kinect Adventures!,X360,2010.0,Misc,15.00,4.89,0.24,1.69,61.0,6.3,E
15,Wii Fit Plus,Wii,2009.0,Sports,9.01,8.49,2.53,1.77,80.0,7.4,E
16,Grand Theft Auto V,PS3,2013.0,Action,7.02,9.09,0.98,3.96,97.0,8.2,M
17,Grand Theft Auto: San Andreas,PS2,2004.0,Action,9.43,0.4,0.41,10.57,95.0,9,M
18,Super Mario World,SNES,1990.0,Platform,12.78,3.75,3.54,0.55,NaN,NaN,NaN
19,Brain Age: Train Your Brain in Minutes a Day,DS,2005.0,Misc,4.74,9.2,4.16,2.04,77.0,7.9,E

In [4]:
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16954 non-null  str
 1   Platform         16956 non-null  str
 2   Year of Release  16681 non-null  float64
 3   Genre            16954 non-null  str
 4   NA sales         16956 non-null  float64
 5   EU sales         16956 non-null  str
 6   JP sales         16956 non-null  str
 7   Other sales      16956 non-null  float64
 8   Critic Score     8242 non-null   float64
 9   User Score       10152 non-null  str
 10  Rating           10085 non-null  str
dtypes: float64(4), str(7)
memory usage: 1.4 MB

В датасете new_games.csv представлены 11 столбцов с общим количеством строк 16956.

**_Типы данных и их корректность_**:
- **Object**: Столбцы этого типа(7): Name, Platform, Genre, EU sales, JP sales, User Score, Rating. Для некоторых столбцов тип данных некорректный, корректно для:  Name, Platform, ведь здесь будут хранится строки с названием игр и платформ. Для столбцов EU sales, JP sales, User Score стоит выбрать тип float64, так как данные столбцы содержат численные значения с плавающей точкой. 

- **float64**: Столбцы этого типа(4): Year of Release, NA sales, Other sales, Critic Score. Данный тип корректный для всех столбцов, кроме Year of Release, так как это год издания, то лучше выбрать тип данных int64 с понижением разрядности, ведь нужен только год.
    
**_Пропуски в данных_**:
Столбец с пропусками в данных будет иметь количество строк отличное от количества строк в датасете. Таким образом, в датасете имеются столбцы с пропусками, а именно: Name, Year of Release, Genre, Critic Score, User Score, Rating. Стоит рассмотреть, какое именно количество пропусков в каждом из столбцов.
    
**_Итог_**: Большинство данных представлены в некорректном типе данных. Названия самих столбцов плохо реализованы, стоит изменить название на snakecase. Также стоит рассмотреть оптимизацию данных через уменьшение разрядности для всех типов float64.

---

## Проверка ошибок в данных и их предобработка


### Названия, или метки, столбцов датафрейма

Вывел названия всех столбцов.

In [5]:
games.columns

Index(['Name', 'Platform', 'Year of Release', 'Genre', 'NA sales', 'EU sales',
       'JP sales', 'Other sales', 'Critic Score', 'User Score', 'Rating'],
      dtype='str')

In [6]:
# Приведение всех названий столбцов к стиле snake case
games.columns = games.columns.str.replace(' ', "_").str.lower()
# Проверка
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16954 non-null  str
 1   platform         16956 non-null  str
 2   year_of_release  16681 non-null  float64
 3   genre            16954 non-null  str
 4   na_sales         16956 non-null  float64
 5   eu_sales         16956 non-null  str
 6   jp_sales         16956 non-null  str
 7   other_sales      16956 non-null  float64
 8   critic_score     8242 non-null   float64
 9   user_score       10152 non-null  str
 10  rating           10085 non-null  str
dtypes: float64(4), str(7)
memory usage: 1.4 MB

### Типы данных

Некорректные типы данных встречаются в столбцах year_of_release, genre, rating, eu_sales, jp_sales, user_score. Возможно, это связано с тем, что в некоторых столбцах, которые должны быть числовыми присутствуют строки по типу: 'Unknown'. Их стоит преобразовать в NaN для дальнейшего анализа столбца.

В столбце year_of_release отсутствуют нечисловые значения, а значит пропуски приведены в формата NaN или None, поэтому сначала стоит обработать пропуски, а потом перевести в формат int64 с понижением разрядности для оптимизации работы.

Преобразование genre и rating стоит сделать после работы с дубликатами, чтобы понимать, какое количество уникальных значений есть в столбцах.

In [7]:
# Обработка столбцов eu_sales, jp_sales и user_score 
for column in ['eu_sales', 'jp_sales', 'user_score']:
    games[column] = pd.to_numeric(games[column], errors='coerce')

games.dtypes

name                   str
platform               str
year_of_release    float64
genre                  str
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
critic_score       float64
user_score         float64
rating                 str
dtype: object

Для оптимизации работы с данными были изменены данные:
- _eu_sales_: object --> float64 
- _jp_sales_: object --> float64
- _user_score_: object --> float64

### Наличие пропусков в данных

- Посчитал количество пропусков в каждом столбце в абсолютных и относительных значениях.

In [8]:
data = {}
# Подсчет относительного и абсолютного значений во всех столбцах
for column in games.columns:
    data[column] = [games[column].isna().sum(), games[column].isna().mean()]

indexes = ['abs_count', 'rel_count']

gaps = pd.DataFrame(data, index=indexes)

gaps

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
abs_count,2.000000,0.0,275.000000,2.000000,0.0,6.000000,4.000000,0.0,8714.000000,9268.000000,6871.000000
rel_count,0.000118,0.0,0.016218,0.000118,0.0,0.000354,0.000236,0.0,0.513918,0.546591,0.405225

Столбцы, которые **_имеют_** пропуски (8): 
- name, 
- year_of_release, 
- genre, 
- eu_sales, 
- jp_sales, 
- critic_score, 
- user_score, 
- rating.

Столбцы, которые **_не имеют_** пропуски (3): 
- platform,
- na_sales,
- other_sales

Наименьшее количество пропусков имеют столбецы с названием игр и их жанром 0.01% , а наибольшее имеют столбцы rating, где пропуски составляют 40,5% и оценка критиков (critic_score) 51,3 %, а самое больше значение принадлежит оценкам пользователей (user_score) 54,7%.

Возможно, данные собирались из разных источников. Также, возможно, заполнение некоторых столбцов необязательно, например, user_score, где пользователь сам решает оставит ли он оценку или нет.

Во всех остальных столбцах, где встречаются пропуски, стоит решить, насколько критичны пропуски. Их можно оставить, заменить или удалить.

In [9]:
# Посмотрим на строки, которые имеют пропуск 
games[games['name'].isna()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
661,NaN,GEN,1993.0,NaN,1.78,0.53,0.00,0.08,NaN,NaN,NaN
14439,NaN,GEN,1993.0,NaN,0.00,0.00,0.03,0.00,NaN,NaN,NaN

Так как в этих 2 строках указан год, который нас не интересует, то принято решение удалить данные строки.

In [10]:
games = games.dropna(subset=['name'])

In [11]:
games[games['year_of_release'].isna()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
183,Madden NFL 2004,PS2,NaN,Sports,4.26,0.26,0.01,0.71,94.0,8.5,E
379,FIFA Soccer 2004,PS2,NaN,Sports,0.59,2.36,0.04,0.51,84.0,6.4,E
458,LEGO Batman: The Videogame,Wii,NaN,Action,1.80,0.97,0.00,0.29,74.0,7.9,E10+
477,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,1.57,1.02,0.00,0.41,NaN,NaN,NaN
611,Space Invaders,2600,NaN,Shooter,2.36,0.14,0.00,0.03,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16609,PDC World Championship Darts 2008,PSP,NaN,Sports,0.01,0.00,0.00,0.00,43.0,NaN,E10+
16641,Freaky Flyers,GC,NaN,Racing,0.01,0.00,0.00,0.00,69.0,6.5,T
16685,Inversion,PC,NaN,Shooter,0.01,0.00,0.00,0.00,59.0,6.7,M
16695,Hakuouki: Shinsengumi Kitan,PS3,NaN,Adventure,0.01,0.00,0.00,0.00,NaN,NaN,NaN
16760,Virtua Quest,GC,NaN,Role-Playing,0.01,0.00,0.00,0.00,55.0,5.5,T

Данные 275 строк не имеют года выхода игры, а значит не попадут в итоговую выборку. Эти строки следует удалить, чтобы перевести столбец year_of_release в int64.

In [12]:
games = games.dropna(subset=['year_of_release'])

games['year_of_release'] = pd.to_numeric(games['year_of_release'], downcast='integer')

games['year_of_release'].dtype

dtype('int16')

In [13]:
f'Кол-во строк после удаления: {games.shape[0]}'

'Кол-во строк после удаления: 16679'

Были удалены строки с отсутсвием года выпуска, так как они не попадут в итоговую выборку. Также был изменен тип данных столбеца year_of_release с float64 на int16 для оптимизации работы.

In [14]:
games[games['genre'].isna()]

Empty DataFrame
Columns: [name, platform, year_of_release, genre, na_sales, eu_sales, jp_sales, other_sales, critic_score, user_score, rating]
Index: []

Строки отсутствуют, так как эти строки удалились ранее. Рассмотрим столбцы, где мало пропущенных строк, чтобы проанализировать данные.

In [15]:
games[games['eu_sales'].isna()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
446,Rhythm Heaven,DS,2008,Misc,0.55,NaN,1.93,0.13,83.0,9.0,E
802,Dead Rising,X360,2006,Action,1.16,NaN,0.08,0.20,85.0,7.6,M
1131,Prince of Persia: Warrior Within,PS2,2004,Action,0.54,NaN,0.00,0.22,83.0,8.5,M
1132,Far Cry 4,XOne,2014,Shooter,0.80,NaN,0.01,0.14,82.0,7.5,M
1394,Sonic Advance 3,GBA,2004,Platform,0.74,NaN,0.08,0.06,79.0,8.4,E
1612,Ratatouille,DS,2007,Action,0.49,NaN,0.00,0.14,NaN,NaN,NaN

In [16]:
games[games['jp_sales'].isna()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
467,Saints Row 2,X360,2008,Action,1.94,0.79,NaN,0.28,81.0,8.1,M
819,UFC 2009 Undisputed,X360,2009,Fighting,1.48,0.39,NaN,0.19,83.0,7.9,T
1379,Hello Kitty Party,DS,2007,Misc,0.78,0.51,NaN,0.12,NaN,NaN,E
4732,Castlevania: The Dracula X Chronicles,PSP,2007,Platform,0.22,0.09,NaN,0.07,80.0,7.8,T

In [17]:
# Кол-во строк, где продажи игры не достигли отметки 10 000.

data = {}

for column in ['na_sales', 'eu_sales', 'jp_sales', 'other_sales']:
        data[column] = (games[column] != 0).sum()

result = pd.DataFrame(data, index=['sales are zero'])
result

                na_sales  eu_sales  jp_sales  other_sales
sales are zero     12166     10835      6218        10089

Так как эти строки с играми, которые в америке набрали в среднем 0.87 млн продаж и в других странах 0,155 млн продаж (при этом кол-во строк со значением 0 в na_sales и other_sales составляет 11006 строк и 10255, соответсвенно ) имеют год издания и жанр, то принято решение оставить эти строки. В данных строках столбцы eu_sales, jp_sales, user_score следует заменить на среднее значением по платформе и году выхода. Также стоит заменить значения critic_score, пропуски которого составляют больше половины.

Перед заменой пропусков стоит посмотреть однородность данных. Изучить максимальные и минимальные значения столбцов: eu_sales, jp_sales, critic_score, user_score.

In [18]:
columns = ['eu_sales', 'jp_sales', 'critic_score', 'user_score']

games[columns].describe()

           eu_sales      jp_sales  critic_score   user_score
count  16673.000000  16675.000000   8085.000000  7558.000000
mean       0.144988      0.078041     68.958689     7.124438
std        0.503693      0.309402     13.923424     1.498803
min        0.000000      0.000000     13.000000     0.000000
25%        0.000000      0.000000     60.000000     6.400000
50%        0.020000      0.000000     71.000000     7.500000
75%        0.110000      0.040000     79.000000     8.200000
max       28.960000     10.220000     98.000000     9.700000

Максимальные значения полученные в столбцах eu_sales, jp_sales сильно выше, чем 3 квантиль, поэтому стоит заменить пропуски на медианное значение. В том время как в столбцах critic_score, user_score данные более однородные, здесь пропуски следует заменить на среднее значение.

В ходе первоначального решение, некоторые данные после группировки ( год издания и платформа ) не имели вообще никакой оценки. Поэтому для таких групп пропуски все равно останустя. Таких строк всего 1598, что составляет почти 10% всех данных, поэтому  данные значения стоит заменить на среднее значение по платформе.

In [19]:
grouped_platforms = games.groupby('platform')[['user_score', 'critic_score']]

grouped_platforms.describe()

         user_score                                                   \
              count      mean       std  min    25%  50%    75%  max
platform
2600            0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
3DO             0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
3DS           172.0  6.853488  1.418276  2.4  6.000  7.1  7.900  9.1
DC             14.0  8.528571  0.916875  6.0  8.175  8.8  9.075  9.4
DS            518.0  7.026834  1.512538  0.0  6.500  7.4  8.000  9.5
GB              0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
GBA           254.0  7.677559  1.435603  1.7  7.100  8.0  8.700  9.6
GC            361.0  7.618283  1.370786  1.4  7.100  8.0  8.500  9.4
GEN             0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
GG              0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
N64             0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
NES             0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
NG              0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
PC            766.0  7.059791  1.543547  1.4  6.200  7.5  8.200  9.3
PCFX            0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
PS            160.0  7.867500  1.341807  1.2  7.300  8.3  8.800  9.4
PS2          1237.0  7.614470  1.315575  1.7  7.000  8.0  8.500  9.5
PS3           873.0  6.723253  1.457163  0.2  6.000  7.1  7.800  9.1
PS4           257.0  6.748249  1.459481  1.5  6.100  7.0  7.800  9.2
PSP           425.0  7.240235  1.216380  0.6  6.700  7.5  8.000  9.7
PSV           145.0  7.342759  1.378241  1.8  7.000  7.6  8.200  9.3
SAT             0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
SCD             0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
SNES            0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
TG16            0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
WS              0.0       NaN       NaN  NaN    NaN  NaN    NaN  NaN
Wii           554.0  6.735740  1.747989  0.2  5.800  7.2  8.000  9.3
WiiU          100.0  6.904000  1.435405  2.7  6.200  7.1  7.925  9.1
X360          957.0  6.674399  1.440465  0.7  5.900  7.0  7.800  9.0
XB            581.0  7.517556  1.464182  0.5  7.000  8.0  8.500  9.3
XOne          184.0  6.520652  1.374597  1.6  5.800  6.8  7.500  9.2

         critic_score
                count       mean        std   min    25%   50%    75%   max
platform
2600              0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
3DO               0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
3DS             167.0  67.089820  12.448364  26.0  58.00  68.0  77.00  92.0
DC               14.0  87.357143   5.865245  80.0  82.25  88.0  89.75  98.0
DS              715.0  63.781818  13.544096  19.0  56.00  66.0  73.00  93.0
GB                0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
GBA             435.0  67.241379  13.446742  23.0  58.00  69.0  77.00  95.0
GC              442.0  69.685520  13.391141  23.0  61.00  70.0  80.00  97.0
GEN               0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
GG                0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
N64               0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
NES               0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
NG                0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
PC              709.0  75.836389  11.344940  33.0  70.00  78.0  84.00  96.0
PCFX              0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
PS              198.0  71.520202  16.717330  26.0  62.00  73.5  85.00  98.0
PS2            1290.0  68.617829  13.045204  24.0  59.25  70.0  78.00  97.0
PS3             816.0  70.455882  14.079721  13.0  61.00  73.0  81.00  98.0
PS4             252.0  72.091270  12.485992  19.0  66.00  73.0  80.00  97.0
PSP             463.0  67.518359  11.534777  28.0  60.00  68.0  76.00  91.0
PSV             122.0  70.909836  10.891656  33.0  64.00  71.0  79.00  93.0
SAT               0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
SCD               0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
SNES              0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
TG16              0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
WS                0.0        NaN        NaN   NaN    NaN   NaN    NaN   NaN
Wii             574.0  62.717770  14.835590  19.0  53.00  65.0  73.00  97.0
WiiU             90.0  70.733333  14.689903  24.0  65.25  73.5  81.00  93.0
X360            908.0  68.557269  15.099962  19.0  59.00  71.0  80.00  98.0
XB              719.0  69.930459  13.797204  19.0  62.00  72.0  80.00  97.0
XOne            171.0  73.309942  12.878293  20.0  66.50  76.0  82.00  97.0

Из результатов видно, что не группировка данных по  году и платформе дает отсутсвие данных, а у некоторых платформ отсутствуют оценки, поэтому стоит рассмотреть решение заполнить пропуски по среднему значению жанра.

In [20]:
grouped_platforms = games.groupby('genre')[['user_score', 'critic_score']]

grouped_platforms.describe()

             user_score                                                    \
                  count      mean       std  min    25%   50%    75%  max
genre
ACTION              7.0  6.571429  1.185628  4.7  5.800  6.90  7.450  7.9
ADVENTURE           0.0       NaN       NaN  NaN    NaN   NaN    NaN  NaN
Action           1807.0  7.057941  1.422526  0.3  6.300  7.40  8.100  9.5
Adventure         301.0  7.158140  1.653998  0.0  6.400  7.60  8.300  9.4
FIGHTING            3.0  6.500000  1.212436  5.8  5.800  5.80  6.850  7.9
Fighting          398.0  7.296985  1.402477  0.9  6.600  7.60  8.300  9.2
MISC                0.0       NaN       NaN  NaN    NaN   NaN    NaN  NaN
Misc              436.0  6.808716  1.546867  0.5  5.975  7.15  8.000  9.2
PLATFORM            2.0  6.500000  0.141421  6.4  6.450  6.50  6.550  6.6
PUZZLE              1.0  4.200000       NaN  4.2  4.200  4.20  4.200  4.2
Platform          426.0  7.310563  1.510016  0.2  6.600  7.70  8.500  9.4
Puzzle            126.0  7.140476  1.510665  1.1  6.325  7.50  8.100  9.3
RACING              3.0  5.166667  0.472582  4.8  4.900  5.00  5.350  5.7
ROLE-PLAYING        3.0  8.533333  0.680686  8.0  8.150  8.30  8.800  9.3
Racing            637.0  7.031397  1.558065  0.3  6.200  7.40  8.200  9.5
Role-Playing      740.0  7.621351  1.090308  1.4  7.100  7.80  8.400  9.7
SHOOTER             5.0  6.840000  0.673053  6.0  6.300  7.00  7.300  7.6
SIMULATION          1.0  3.300000       NaN  3.3  3.300  3.30  3.300  3.3
SPORTS              2.0  6.050000  0.212132  5.9  5.975  6.05  6.125  6.2
STRATEGY            0.0       NaN       NaN  NaN    NaN   NaN    NaN  NaN
Shooter           917.0  7.050709  1.503167  1.2  6.300  7.40  8.100  9.3
Simulation        343.0  7.144898  1.614036  2.1  6.550  7.50  8.300  9.6
Sports           1091.0  6.955545  1.616150  0.2  6.100  7.40  8.100  9.5
Strategy          309.0  7.296117  1.632220  0.6  6.800  7.80  8.400  9.4

             critic_score                                                  \
                    count       mean        std   min    25%   50%    75%
genre
ACTION                7.0  64.857143  16.190826  42.0  52.00  72.0  75.50
ADVENTURE             0.0        NaN        NaN   NaN    NaN   NaN    NaN
Action             1859.0  66.676708  14.175980  19.0  57.00  68.0  77.00
Adventure           324.0  65.324074  13.950040  17.0  57.00  66.0  76.00
FIGHTING              3.0  67.000000  19.078784  49.0  57.00  65.0  76.00
Fighting            407.0  69.125307  14.280322  23.0  60.50  72.0  80.00
MISC                  1.0  49.000000        NaN  49.0  49.00  49.0  49.00
Misc                517.0  66.657640  13.971483  19.0  59.00  69.0  76.00
PLATFORM              2.0  59.500000   0.707107  59.0  59.25  59.5  59.75
PUZZLE                1.0  73.000000        NaN  73.0  73.00  73.0  73.00
Platform            494.0  68.032389  13.253304  19.0  59.00  69.0  77.75
Puzzle              221.0  67.199095  12.743490  25.0  60.00  70.0  76.00
RACING                4.0  66.750000  14.407753  52.0  58.75  64.5  72.50
ROLE-PLAYING          3.0  71.333333  17.387735  58.0  61.50  65.0  78.00
Racing              735.0  67.990476  14.269923  13.0  59.00  69.0  79.50
Role-Playing        734.0  72.619891  11.976270  35.0  65.00  73.5  82.00
SHOOTER               4.0  72.250000   4.787136  67.0  69.25  72.0  75.00
SIMULATION            1.0  33.000000        NaN  33.0  33.00  33.0  33.00
SPORTS                4.0  62.000000  17.644640  36.0  58.50  69.5  73.00
STRATEGY              0.0        NaN        NaN   NaN    NaN   NaN    NaN
Shooter             936.0  70.181624  14.497174  27.0  61.00  73.0  81.00
Simulation          352.0  68.735795  12.428993  31.0  62.00  70.0  77.25
Sports             1176.0  71.934524  13.950733  19.0  64.00  75.0  82.00
Strategy            300.0  72.186667  11.704778  35.0  65.75  73.0  80.00


               max
genre
ACTION        85.0
ADVENTURE      NaN
Action        98.0
Adventure     93.0
FIGHTING      87.0
Fighting      98.0
MISC          49.0
Misc          93.0
PLATFORM      60.0
PUZZLE        73.0
Platform      97.0
Puzzle        90.0
RACING        86.0
ROLE-PLAYING  91.0
Racing        96.0
Role-Playing  96.0
SHOOTER       78.0
SIMULATION    33.0
SPORTS        73.0
STRATEGY       NaN
Shooter       97.0
Simulation    92.0
Sports        98.0
Strategy      94.0

В результате видны неявные дубликаты, поэтому стоит сначала обработать дубликаты, а потом посмотреть однородность данных и заменить пропуски, поэтомум сейчас заполним только столбцы eu_sales, jp_sales.

In [21]:
columns = ['eu_sales', 'jp_sales']

for column in columns:  
    median = games.groupby(['platform', 'year_of_release'])[column].transform('median')
    games[column].fillna(value=median, inplace=True)
# Проверка измененных значений
for column in columns:  
        print(f'Кол-во пропусков в столбце {column}: {(games[column].isna()).sum()}')

Кол-во пропусков в столбце eu_sales: 6
Кол-во пропусков в столбце jp_sales: 4

C:\Users\semen\AppData\Local\Temp\ipykernel_18864\2711046438.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  games[column].fillna(value=median, inplace=True)

###  Явные и неявные дубликаты в данных

Рассмотрим уникальные значения в категориальных столбцах - name, platform, year_of_release, genre

In [22]:
columns = ['platform', 'year_of_release', 'genre']

for column in columns:
    print(f'Уникальные значения столбца {column}: ', games[column].unique(), '\n')

Уникальные значения столбца platform:  <StringArray>
[ 'Wii',  'NES',   'GB',   'DS', 'X360',  'PS3',  'PS2', 'SNES',  'GBA',
  'PS4',  '3DS',  'N64',   'PS',   'XB',   'PC', '2600',  'PSP', 'XOne',
 'WiiU',   'GC',  'GEN',   'DC',  'PSV',  'SAT',  'SCD',   'WS',   'NG',
 'TG16',  '3DO',   'GG', 'PCFX']
Length: 31, dtype: str

Уникальные значения столбца year_of_release:  [2006 1985 2008 2009 1996 1989 1984 2005 1999 2007 2010 2013 2004 1990
 1988 2002 2001 2011 1998 2015 2012 2014 1992 1997 1993 1994 1982 2016
 2003 1986 2000 1995 1991 1981 1987 1980 1983]

Уникальные значения столбца genre:  <StringArray>
[      'Sports',     'Platform',       'Racing', 'Role-Playing',
       'Puzzle',         'Misc',      'Shooter',   'Simulation',
       'Action',     'Fighting',    'Adventure',     'Strategy',
         'MISC', 'ROLE-PLAYING',       'RACING',       'ACTION',
      'SHOOTER',     'FIGHTING',       'SPORTS',     'PLATFORM',
    'ADVENTURE',   'SIMULATION',       'PUZZLE',     'STRATEGY']
Length: 24, dtype: str

Данные в столбцах platform и year_of_release приведены корректно. В столбце genre встречаются неявные дубликаты: некоторые жанры написаны заглавными буквами, приведем все названия жанров к нижнему регистру.

In [23]:
games['genre'] = games['genre'].str.lower()
# Проверка
games['genre'].unique()

<StringArray>
[      'sports',     'platform',       'racing', 'role-playing',
       'puzzle',         'misc',      'shooter',   'simulation',
       'action',     'fighting',    'adventure',     'strategy']
Length: 12, dtype: str

Данные нормализованы, теперь можно рассмотреть возможность замены оценок по жанру игры.

In [24]:
grouped_platforms = games.groupby('genre')[['user_score', 'critic_score']]

grouped_platforms.describe()

             user_score                                                  \
                  count      mean       std  min    25%   50%  75%  max
genre
action           1814.0  7.056064  1.421734  0.3  6.300  7.40  8.1  9.5
adventure         301.0  7.158140  1.653998  0.0  6.400  7.60  8.3  9.4
fighting          401.0  7.291022  1.401524  0.9  6.600  7.60  8.3  9.2
misc              436.0  6.808716  1.546867  0.5  5.975  7.15  8.0  9.2
platform          428.0  7.306776  1.507507  0.2  6.575  7.70  8.5  9.4
puzzle            127.0  7.117323  1.527114  1.1  6.300  7.50  8.1  9.3
racing            640.0  7.022656  1.559845  0.3  6.200  7.40  8.2  9.5
role-playing      743.0  7.625034  1.090213  1.4  7.100  7.80  8.4  9.7
shooter           922.0  7.049566  1.499817  1.2  6.300  7.40  8.1  9.3
simulation        344.0  7.133721  1.624959  2.1  6.500  7.50  8.3  9.6
sports           1093.0  6.953888  1.615146  0.2  6.100  7.40  8.1  9.5
strategy          309.0  7.296117  1.632220  0.6  6.800  7.80  8.4  9.4

             critic_score                                                  \
                    count       mean        std   min    25%   50%    75%
genre
action             1866.0  66.669882  14.179558  19.0  57.00  68.0  77.00
adventure           324.0  65.324074  13.950040  17.0  57.00  66.0  76.00
fighting            410.0  69.109756  14.291419  23.0  60.25  72.0  80.00
misc                518.0  66.623552  13.979509  19.0  59.00  69.0  76.00
platform            496.0  67.997984  13.237611  19.0  59.00  69.0  77.25
puzzle              222.0  67.225225  12.720586  25.0  60.00  70.0  75.75
racing              739.0  67.983762  14.261106  13.0  59.00  69.0  79.50
role-playing        737.0  72.614654  11.986437  35.0  65.00  73.0  82.00
shooter             940.0  70.190426  14.469420  27.0  61.75  73.0  81.00
simulation          353.0  68.634561  12.556221  31.0  62.00  70.0  77.00
sports             1180.0  71.900847  13.967410  19.0  64.00  75.0  82.00
strategy            300.0  72.186667  11.704778  35.0  65.75  73.0  80.00


               max
genre
action        98.0
adventure     93.0
fighting      98.0
misc          93.0
platform      97.0
puzzle        90.0
racing        96.0
role-playing  96.0
shooter       97.0
simulation    92.0
sports        98.0
strategy      94.0

Теперь у каждой группы есть оценки, данные выглядят однородными. Пропуски можно заменить на среднее значение по жанру.

In [25]:
columns = ['user_score', 'critic_score']

for column in columns:
    mean_of_genre = games.groupby('genre')[column].transform('mean')
    games[column] = games[column].fillna(mean_of_genre)

# Проверка
for column in columns:
    print(f'Кол-во пропусков в {column}: {games[column].isna().sum()}')

Кол-во пропусков в user_score: 0
Кол-во пропусков в critic_score: 0

In [26]:
# стоит проверить дубликаты по названию игры и платформе
games.duplicated(subset=['name', 'platform']).sum()

np.int64(238)

Результат 238, а значит есть строки, которые описывают одну и ту же игру.

In [27]:
games[games.duplicated(subset=['name', 'platform'])]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
268,Batman: Arkham Asylum,PS3,2009,action,2.24,1.31,0.07,0.61,91.000000,8.900000,T
368,James Bond 007: Agent Under Fire,PS2,2001,shooter,1.90,1.13,0.10,0.41,72.000000,7.900000,T
717,God of War: Ascension,PS3,2013,action,1.23,0.63,0.04,0.35,80.000000,7.500000,M
823,Wipeout: The Game,Wii,2009,misc,1.94,0.00,0.00,0.12,66.623552,6.808716,NaN
848,Rayman Raving Rabbids: TV Party,Wii,2008,misc,0.72,1.08,0.00,0.23,73.000000,7.700000,E10+
...,...,...,...,...,...,...,...,...,...,...,...
16671,Fullmetal Alchemist: Prince of the Dawn,Wii,2009,adventure,0.00,0.00,0.01,0.00,65.324074,7.158140,NaN
16753,Routes PE,PS2,2007,adventure,0.00,0.00,0.01,0.00,65.324074,7.158140,NaN
16799,Transformers: Prime,Wii,2012,action,0.00,0.01,0.00,0.00,66.669882,7.056064,NaN
16912,Metal Gear Solid V: The Definitive Experience,XOne,2016,action,0.01,0.00,0.00,0.00,66.669882,7.056064,M
16940,The Longest 5 Minutes,PSV,2016,action,0.00,0.00,0.01,0.00,66.669882,7.056064,NaN

Принято решение удалить повторяющиеся строки.

In [28]:
games.drop_duplicates(subset=['name', 'platform'], inplace=True)

In [29]:
# Кол-во строк после удаления
f'Кол-во строк после удаления: {games.shape[0]}'

'Кол-во строк после удаления: 16441'

In [30]:
# итоговая проверка
games.duplicated().sum()

np.int64(0)

После удаления в датафрейме отсутствуют явные дубликаты.

Были обнаружены неявные дубликаты в столбце genre. Они возникли из-за различий в регистре символов. После нормализации регистра значения были приведены к единому виду. Далее была выполнена проверка на наличие повторяющихся записей по комбинации name и platform. Было найдено 238 повторяющихся строк. Дубликаты были удалены.Повторная проверка показала отсутствие дубликатов.

In [31]:
initial_rows = 16956

print(f'Кол-во удаленных строк в датафрейме: {initial_rows - games.shape[0]}')
print(f'Доля удаленных строк в датафрейме: {round((initial_rows - games.shape[0]) / initial_rows,2)}')

Кол-во удаленных строк в датафрейме: 515
Доля удаленных строк в датафрейме: 0.03

Итого: 
- обработаны пропуски:
    - пропуски в eu_sales
    - jp_sales заполнялись по платформе и году выпуска;
пропуски в user_score и critic_score заполнялись по жанру.
- жанры приведены к единому регистру, устранены неявные дубликаты
- найдены и удалены явные дубликаты
- удалены строки, содержащие критически важные пропуски, удалено 515 строк ( 3% )

---

## Фильтрация данных

In [32]:
# Так нужен срез датафрейма, использую метод copy(),
# иначе df_actual будет хранить в себе лишь ссылку на исходны датафрейм games,
# и pandas будет предупреждать о люом измненение в df_actual
df_actual = games[games['year_of_release'].between(2000,2013)].copy()
df_actual.info()

<class 'pandas.DataFrame'>
Index: 12778 entries, 0 to 16954
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             12778 non-null  str
 1   platform         12778 non-null  str
 2   year_of_release  12778 non-null  int16
 3   genre            12778 non-null  str
 4   na_sales         12778 non-null  float64
 5   eu_sales         12773 non-null  float64
 6   jp_sales         12774 non-null  float64
 7   other_sales      12778 non-null  float64
 8   critic_score     12778 non-null  float64
 9   user_score       12778 non-null  float64
 10  rating           8720 non-null   str
dtypes: float64(6), int16(1), str(4)
memory usage: 1.1 MB

Для дальнейшего анализа был выделен актуальный период с 2000 по 2013 год включительно. После фильтрации в датафрейме осталось 12778 записей.

---

## Категоризация данных
    
- Разделил все игры по оценкам пользователей: высокая оценка (от 8 до 10 включительно), средняя оценка (от 3 до 8, не включая правую границу интервала) и низкая оценка (от 0 до 3, не включая правую границу интервала).

In [33]:
categories = ['низкая оценка', 'средняя оценка', 'высокая оценка']

# Расширил верхнюю границу, чтобы игры, где оценка 10 тоже получили категорию
# Предварительно были рассмотренны максимальные значения оценок, где макс составлял 9.7.
df_actual['category_by_user'] = pd.cut(df_actual['user_score'], bins=[0, 3, 8, 10.1], labels=categories, right=False, include_lowest=True)

# Проверка
df_actual[['user_score', 'category_by_user']]

       user_score category_by_user
0        8.000000   высокая оценка
2        8.300000   высокая оценка
3        8.000000   высокая оценка
6        8.500000   высокая оценка
7        6.600000   средняя оценка
...           ...              ...
16947    7.049566   средняя оценка
16949    7.306776   средняя оценка
16950    7.022656   средняя оценка
16952    6.953888   средняя оценка
16954    7.306776   средняя оценка

[12778 rows x 2 columns]

- Похожим образом разделил игры по оценкам критиков: высокая оценка (от 80 до 100 включительно), средняя оценка (от 30 до 80, не включая правую границу интервала) и низкая оценка (от 0 до 30, не включая правую границу интервала).

In [34]:
# Расширил верхнюю границу, чтобы игры, где оценка 100 тоже получили категорию
# Предварительно были рассмотренны максимальные значения оценок, где макс составлял 98.
df_actual['category_by_critic'] = pd.cut(df_actual['critic_score'], bins=[0, 30, 80, 100.1], labels=categories, right=False, include_lowest=True)

# Проверка
df_actual[['critic_score', 'category_by_critic']]

       critic_score category_by_critic
0         76.000000     средняя оценка
2         82.000000     высокая оценка
3         80.000000     высокая оценка
6         89.000000     высокая оценка
7         58.000000     средняя оценка
...             ...                ...
16947     70.190426     средняя оценка
16949     67.997984     средняя оценка
16950     67.983762     средняя оценка
16952     71.900847     средняя оценка
16954     67.997984     средняя оценка

[12778 rows x 2 columns]

In [35]:
df_actual.groupby('category_by_user')['name'].count()

category_by_user
низкая оценка       116
средняя оценка    10378
высокая оценка     2284
Name: name, dtype: int64

In [36]:
df_actual.groupby('category_by_critic')['name'].count()

category_by_critic
низкая оценка        55
средняя оценка    11034
высокая оценка     1689
Name: name, dtype: int64

In [37]:
df_actual.groupby(['category_by_user', 'category_by_critic'])['name'].count()

category_by_user  category_by_critic
низкая оценка     низкая оценка           17
                  средняя оценка          98
                  высокая оценка           1
средняя оценка    низкая оценка           37
                  средняя оценка        9668
                  высокая оценка         673
высокая оценка    низкая оценка            1
                  средняя оценка        1268
                  высокая оценка        1015
Name: name, dtype: int64

- Выделил топ-7 платформ по количеству игр, выпущенных за весь актуальный период.

In [38]:
df_actual.groupby('platform')['name'].count().sort_values(ascending=False)[:7]

platform
PS2     2127
DS      2120
Wii     1275
PSP     1180
X360    1120
PS3     1086
GBA      811
Name: name, dtype: int64

Игры были разделены на категории по пользовательским оценкам и по оценкам критиков:
- низкая оценка
- средняя оценка
- высокая оценка

Были определены наиболее популярные платформы по количеству выпущенных игр за актуальный период, выделен топ-7 платформ.

---

## Итоговый вывод

Были загружены данные new_games.csv. Они содержат 11 столбцов и 16956 строк, в которых представлена информация о характеристиках игр. При первичном знакомстве с данными и их предобработке получили такие результаты:
- Названия столбцов приведены к единому виду snake case
- В 8 столбцах ('name', 'year_of_release', 'genre', 'eu_sales', 'jp_sales', 'critic_score', 'user_score', 'rating') были обнаружены пропущенные значения. Максимальное значение пропущенных данных в столбце 'user_score' — 54,7%. Пропуски в столбцах 'eu_sales', 'jp_sales' были заменены медианными значениями по столбцам по платформе и году выпуска, а пропуски по столбцам 'critic_score', 'user_score' заменены на средние значения жанра.
- Для оптимизации работы с данными в датафрейме были произведены следующие изменения типов данных:
  - 'eu_sales', 'jp_sales', 'user_score': с object на  float64
  - 'year_of_release': с float64 на int16
- Были найдены неявные дубликаты в столбце genre, после чего выполнена нормализация значений. Также обнаружено и удалено 238 явных дубликатов.
- Были удалены 515 строк ( дубликаты и строки, которые не попадут в итоговую выборку), что составляет 3% от исходного датасета.
- Был сформирован срез данных - df_actual, где рассматривались игры с 'year_of_release' от 2000 до 2013 года. Новый срез данных имеет 12778 строк.
- Для дополнительной работы с данными были созданы дополнительные столбцы:
    - 'category_by_user': категория игры по оценкам пользователей - низкая, средняя и высокая 
    - 'category_by_critic': категория игры по оценкам критиков - низкая, средняя и высокая